name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # এখানে gradle-version বাড়িয়ে ৮.৯ করা হয়েছে যাতে Android Plugin এরর না দেয়
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: '8.9' 

    # wrapper jar ছাড়া সরাসরি global gradle দিয়ে বিল্ড করা হচ্ছে
    - name: Build with Gradle
      run: gradle build
